default: &default
  adapter: mysql2
  reconnect: true
  encoding: utf8mb4
  pool: 20
  host: localhost
  username: user
  password: pass
  port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>

development:
  <<: *default
  database: base_development

test:
  <<: *default
  database: base_test

staging:
  <<: *default
  database: base_staging

production:
  <<: *default
  database: base_production
